exports.leagueTables = {
  Niemcy: [
    {
      name: "1. FC Union Berlin",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Eintracht Frankfurt",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Bayern Monachium",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Bayer Leverkusen",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "VfL Wolfsburg",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Hertha Berlin",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Bochum",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Borussia Dortmund",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Arminia Bielefeld",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "B. Moenchengladbach",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "TSG Hoffenheim",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "1. FC Koeln",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "1. FSV Mainz 05",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "SC Freiburg",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "Furth",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "FC Augsburg",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "VfB Stuttgart",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
    {
      name: "RB Lipsk",
      matches: 0,
      wins: 0,
      draws: 0,
      losers: 0,
      goalsScored: 0,
      goalsConceded: 0,
      points: 0,
    },
  ],
};
